#!/usr/bin/env ts-node
/**
 * tools/prisma-merge/index.ts
 *
 * Merges split Prisma schema files into a single merged.prisma
 * for use with `prisma migrate` and `prisma db push`.
 *
 * Usage:
 *   ts-node tools/prisma-merge/index.ts
 *   # → writes prisma/merged.prisma
 *
 * In CI / package.json:
 *   "prisma:merge": "ts-node tools/prisma-merge/index.ts"
 *   "prisma:migrate": "npm run prisma:merge && prisma migrate dev --schema=prisma/merged.prisma"
 */

import * as fs from 'fs'
import * as path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const ROOT = path.resolve(__dirname, '../..')
const PRISMA_DIR = path.join(ROOT, 'prisma')
const OUTPUT = path.join(PRISMA_DIR, 'merged.prisma')

// Order matters: engine first (defines datasource + generator defaults)
const SCHEMA_FILES = [
  'schema.prisma',      // original (authoritative until R2 is complete)
  // After R2 full split, uncomment below and remove schema.prisma:
  // 'engine.prisma',
  // 'business.prisma',
  // 'ochag.prisma',
  // 'freeclaude.prisma',
]

interface SchemaSection {
  datasource: string | null
  generators: string[]
  models: string[]
  enums: string[]
  other: string[]
}

function parseSchema(content: string): SchemaSection {
  const section: SchemaSection = {
    datasource: null,
    generators: [],
    models: [],
    enums: [],
    other: [],
  }

  // Simple block-level parser
  let pos = 0
  while (pos < content.length) {
    // Skip whitespace and comments
    const lineMatch = content.slice(pos).match(/^\/\/[^\n]*\n?/)
    if (lineMatch) { pos += lineMatch[0].length; continue }

    const blockMatch = content.slice(pos).match(/^(datasource|generator|model|enum)\s+\w+\s*\{/)
    if (!blockMatch) {
      const newline = content.indexOf('\n', pos)
      if (newline === -1) break
      pos = newline + 1
      continue
    }

    const blockType = blockMatch[1]
    const start = pos
    let depth = 0
    let end = pos
    for (let i = pos; i < content.length; i++) {
      if (content[i] === '{') depth++
      if (content[i] === '}') {
        depth--
        if (depth === 0) { end = i + 1; break }
      }
    }

    const block = content.slice(start, end).trim()
    pos = end

    if (blockType === 'datasource') section.datasource = block
    else if (blockType === 'generator') section.generators.push(block)
    else if (blockType === 'model') section.models.push(block)
    else if (blockType === 'enum') section.enums.push(block)
    else section.other.push(block)
  }

  return section
}

function merge(files: string[]): string {
  const allSections: SchemaSection[] = []
  let canonicalDatasource: string | null = null
  const canonicalGenerators: string[] = []
  const allModels: string[] = []
  const allEnums: string[] = []
  const seenModels = new Set<string>()
  const seenGenerators = new Set<string>()

  for (const file of files) {
    const fullPath = path.join(PRISMA_DIR, file)
    if (!fs.existsSync(fullPath)) {
      console.warn(`⚠️  Skipping missing file: ${file}`)
      continue
    }

    const content = fs.readFileSync(fullPath, 'utf-8')
    const section = parseSchema(content)

    if (section.datasource && !canonicalDatasource) {
      canonicalDatasource = section.datasource
    }

    for (const gen of section.generators) {
      const nameMatch = gen.match(/generator\s+(\w+)/)
      const name = nameMatch ? nameMatch[1] : gen
      if (!seenGenerators.has(name)) {
        seenGenerators.add(name)
        // Only include the default `client` generator in merged output
        if (name === 'client') canonicalGenerators.push(gen)
      }
    }

    for (const model of section.models) {
      const nameMatch = model.match(/model\s+(\w+)/)
      const name = nameMatch ? nameMatch[1] : model
      if (!seenModels.has(name)) {
        seenModels.add(name)
        allModels.push(model)
      }
    }

    for (const en of section.enums) {
      allEnums.push(en)
    }
  }

  const parts: string[] = [
    '// ============================================================',
    '// MERGED PRISMA SCHEMA — auto-generated by tools/prisma-merge',
    '// DO NOT EDIT MANUALLY — edit engine.prisma / business.prisma / etc.',
    `// Generated: ${new Date().toISOString()}`,
    '// ============================================================',
    '',
    '// Default client generator for migrations',
    'generator client {',
    '  provider = "prisma-client-js"',
    '}',
    '',
  ]

  if (canonicalDatasource) {
    parts.push(canonicalDatasource, '')
  }

  for (const model of allModels) {
    parts.push(model, '')
  }

  for (const en of allEnums) {
    parts.push(en, '')
  }

  return parts.join('\n')
}

function main() {
  console.log('🔀 prisma-merge: merging schemas...')
  for (const f of SCHEMA_FILES) {
    console.log(`  - ${f}`)
  }

  const merged = merge(SCHEMA_FILES)
  fs.writeFileSync(OUTPUT, merged)

  const modelCount = (merged.match(/^model \w+/gm) || []).length
  console.log(`✅ Written: prisma/merged.prisma (${modelCount} models)`)
  console.log(`   Run: prisma migrate dev --schema=prisma/merged.prisma`)
}

main()
