// Generated by scripts/sync-public-docs.mjs — do not edit by hand.
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Getting started',
      collapsed: false,
      items: [
        'intro',
        'quickstart',
        'architecture',
        'governance',
      ],
    },
    {
      type: 'category',
      label: 'Universal Engine',
      collapsed: true,
      items: [
        'universal-engine/index',
        'universal-engine/strategy-and-goals',
        'universal-engine/architecture',
        'universal-engine/lifecycle',
        'universal-engine/multi-agent-topology',
        'universal-engine/tool-model',
        'universal-engine/memory-and-strategy',
        'universal-engine/safety-and-governance',
        'universal-engine/multi-model-policy',
        'universal-engine/api-cli-vscode',
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      collapsed: false,
      items: [
        'integrations',
        'contracts/gateway-streaming',
      ],
    },
    {
      type: 'category',
      label: 'Releases',
      collapsed: false,
      items: [
        'releases/v0.3.0',
      ],
    },
  ],
};

export default sidebars;
