import type { RunRecord } from './run-lifecycle';
import type { DeliveryEvidenceSnapshot } from './github-delivery-evidence';

export interface GitHubDeliveryPlanInput {
  run: RunRecord;
  evidence: DeliveryEvidenceSnapshot;
  evidenceArtifactId?: string;
  issueNumber?: number;
  title?: string;
  body?: string;
}

export interface GitHubDeliveryPlan {
  schemaVersion: 'pyrfor.github_delivery_plan.v1';
  createdAt: string;
  runId: string;
  mode: 'dry_run';
  applySupported: false;
  repository: string | null;
  baseBranch: string | null;
  headSha: string | null;
  proposedBranch: string;
  pullRequest: {
    title: string;
    body: string;
    draft: true;
  };
  issue?: {
    number: number;
    commentBody: string;
  };
  ci: {
    observeWorkflowRuns: Array<{
      id: number;
      name?: string;
      status?: string;
      conclusion?: string | null;
      url?: string;
    }>;
  };
  blockers: string[];
  evidenceArtifactId?: string;
}

export function buildGithubDeliveryPlan(input: GitHubDeliveryPlanInput): GitHubDeliveryPlan {
  const title = normalizeTitle(input.title) ?? defaultTitle(input.run);
  const body = normalizeBody(input.body) ?? defaultPullRequestBody(input.run, input.evidence);
  const issueNumber = input.issueNumber ?? input.evidence.github.issue?.number;
  const proposedBranch = proposedDeliveryBranch(input.run, input.evidence);
  const blockers = collectBlockers(input.evidence, proposedBranch);
  return {
    schemaVersion: 'pyrfor.github_delivery_plan.v1',
    createdAt: new Date().toISOString(),
    runId: input.run.run_id,
    mode: 'dry_run',
    applySupported: false,
    repository: input.evidence.github.repository ?? input.evidence.git.remote?.repository ?? null,
    baseBranch: input.evidence.git.branch,
    headSha: input.evidence.git.headSha,
    proposedBranch,
    pullRequest: {
      title,
      body,
      draft: true,
    },
    ...(issueNumber ? {
      issue: {
        number: issueNumber,
        commentBody: defaultIssueComment(input.run, input.evidence),
      },
    } : {}),
    ci: {
      observeWorkflowRuns: input.evidence.github.workflowRuns.slice(0, 5).map((run) => ({
        id: run.id,
        ...(run.name ? { name: run.name } : {}),
        ...(run.status ? { status: run.status } : {}),
        ...(run.conclusion !== undefined ? { conclusion: run.conclusion } : {}),
        ...(run.url ? { url: run.url } : {}),
      })),
    },
    blockers,
    ...(input.evidenceArtifactId ? { evidenceArtifactId: input.evidenceArtifactId } : {}),
  };
}

function collectBlockers(evidence: DeliveryEvidenceSnapshot, proposedBranch: string): string[] {
  const blockers: string[] = [];
  if (evidence.verifierStatus !== 'passed' && evidence.verifierStatus !== 'warning') {
    blockers.push(`verifier status is ${evidence.verifierStatus ?? 'unknown'}`);
  }
  if (!evidence.git.available) blockers.push('local git evidence is unavailable');
  if (!evidence.git.headSha) blockers.push('HEAD sha is unavailable');
  if (!evidence.github.repository && !evidence.git.remote?.repository) blockers.push('GitHub repository is unavailable');
  if (evidence.git.dirtyFiles.length > 0) blockers.push(`workspace has ${evidence.git.dirtyFiles.length} dirty file(s)`);
  const openForBranch = evidence.github.pullRequests.find((pr) => (
    pr.state === 'open' && (pr.headRef === proposedBranch || pr.headRef === evidence.git.branch)
  ));
  if (openForBranch) blockers.push(`open PR already exists: #${openForBranch.number}`);
  for (const error of evidence.github.errors.slice(0, 3)) {
    blockers.push(`GitHub ${error.scope}: ${error.message}`);
  }
  return blockers;
}

function proposedDeliveryBranch(run: RunRecord, evidence: DeliveryEvidenceSnapshot): string {
  const suffix = slugify(run.task_id || run.run_id).slice(0, 48) || 'delivery';
  const sha = evidence.git.headSha?.slice(0, 8) ?? run.run_id.slice(0, 8);
  return `pyrfor/${suffix}-${sha}`;
}

function defaultTitle(run: RunRecord): string {
  const task = run.task_id || run.run_id;
  return `Pyrfor delivery: ${task.slice(0, 90)}`;
}

function defaultPullRequestBody(run: RunRecord, evidence: DeliveryEvidenceSnapshot): string {
  const lines = [
    'Generated by Pyrfor as a dry-run delivery plan. No GitHub writes were performed.',
    '',
    `Run: ${run.run_id}`,
    `Verifier: ${evidence.verifierStatus ?? 'unknown'}`,
    `Head: ${evidence.git.headSha ?? 'unknown'}`,
  ];
  if (evidence.deliveryChecklist.length > 0) {
    lines.push('', 'Delivery checklist:', ...evidence.deliveryChecklist.map((item) => `- ${item}`));
  }
  if (evidence.summary) {
    lines.push('', 'Summary:', evidence.summary);
  }
  return lines.join('\n');
}

function defaultIssueComment(run: RunRecord, evidence: DeliveryEvidenceSnapshot): string {
  return [
    `Pyrfor prepared a dry-run delivery plan for run ${run.run_id}.`,
    `Verifier: ${evidence.verifierStatus ?? 'unknown'}.`,
    `Head: ${evidence.git.headSha ?? 'unknown'}.`,
  ].join('\n');
}

function normalizeTitle(value?: string): string | null {
  const trimmed = value?.trim();
  return trimmed ? trimmed.slice(0, 120) : null;
}

function normalizeBody(value?: string): string | null {
  const trimmed = value?.trim();
  return trimmed || null;
}

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .replace(/-{2,}/g, '-');
}
