"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.getOrchestrationOpsSnapshot = exports.syncWorkflowStepFromHeartbeatRun = exports.getWorkflowRunDetail = exports.listWorkflowRuns = exports.advanceWorkflowRun = exports.createWorkflowRun = exports.listWorkflowTemplates = exports.getWorkflowTemplate = exports.updateWorkflowTemplate = exports.createWorkflowTemplate = exports.updateDelegationStatusByChildRun = exports.listWorkflowDelegations = exports.listRunDelegations = exports.createAgentDelegation = exports.queueHeartbeatRunReplay = exports.parseCheckpointState = exports.listHeartbeatRunCheckpoints = exports.createHeartbeatRunCheckpoint = exports.recordAgentCircuitSuccess = exports.recordAgentCircuitFailure = exports.isAgentCircuitOpen = exports.getAgentCircuitSnapshot = exports.ensureAgentCircuitReady = exports.AgentCircuitOpenError = exports.resolveMaxRetries = exports.computeRetryDelayMs = exports.classifyOrchestrationFailure = exports.buildWakeupIdempotencyKey = exports.applyWakeupFailure = exports.resolveSecretRefs = exports.deleteSecret = exports.listSecrets = exports.getSecret = exports.setSecret = exports.sendBudgetWarningTelegram = exports.sendHeartbeatTelegramNotification = exports.WebhookAdapter = exports.OpenClawAdapter = exports.registerAdapter = exports.getAdapter = exports.getPreset = exports.AGENT_PRESETS = exports.cronMatchesNow = exports.enqueueScheduledHeartbeatWakeups = exports.processHeartbeatQueue = exports.runHeartbeatScheduler = exports.checkBudget = exports.processWakeupQueue = exports.executeHeartbeatRun = exports.jobQueue = void 0;
exports.setPermissions = exports.listPermissions = exports.revokePermission = exports.grantPermission = exports.requirePermission = exports.hasPermission = void 0;
// Agent Orchestration Layer — public API
__exportStar(require("./types"), exports);
__exportStar(require("./error-utils"), exports);
__exportStar(require("./agent-service"), exports);
__exportStar(require("./goal-service"), exports);
__exportStar(require("./actor"), exports);
var job_queue_1 = require("./job-queue");
Object.defineProperty(exports, "jobQueue", { enumerable: true, get: function () { return job_queue_1.jobQueue; } });
var heartbeat_executor_1 = require("./heartbeat-executor");
Object.defineProperty(exports, "executeHeartbeatRun", { enumerable: true, get: function () { return heartbeat_executor_1.executeHeartbeatRun; } });
Object.defineProperty(exports, "processWakeupQueue", { enumerable: true, get: function () { return heartbeat_executor_1.processWakeupQueue; } });
Object.defineProperty(exports, "checkBudget", { enumerable: true, get: function () { return heartbeat_executor_1.checkBudget; } });
var heartbeat_scheduler_1 = require("./heartbeat-scheduler");
Object.defineProperty(exports, "runHeartbeatScheduler", { enumerable: true, get: function () { return heartbeat_scheduler_1.runHeartbeatScheduler; } });
Object.defineProperty(exports, "processHeartbeatQueue", { enumerable: true, get: function () { return heartbeat_scheduler_1.processHeartbeatQueue; } });
Object.defineProperty(exports, "enqueueScheduledHeartbeatWakeups", { enumerable: true, get: function () { return heartbeat_scheduler_1.enqueueScheduledHeartbeatWakeups; } });
Object.defineProperty(exports, "cronMatchesNow", { enumerable: true, get: function () { return heartbeat_scheduler_1.cronMatchesNow; } });
var agent_presets_1 = require("./agent-presets");
Object.defineProperty(exports, "AGENT_PRESETS", { enumerable: true, get: function () { return agent_presets_1.AGENT_PRESETS; } });
Object.defineProperty(exports, "getPreset", { enumerable: true, get: function () { return agent_presets_1.getPreset; } });
var adapters_1 = require("./adapters");
Object.defineProperty(exports, "getAdapter", { enumerable: true, get: function () { return adapters_1.getAdapter; } });
Object.defineProperty(exports, "registerAdapter", { enumerable: true, get: function () { return adapters_1.registerAdapter; } });
Object.defineProperty(exports, "OpenClawAdapter", { enumerable: true, get: function () { return adapters_1.OpenClawAdapter; } });
Object.defineProperty(exports, "WebhookAdapter", { enumerable: true, get: function () { return adapters_1.WebhookAdapter; } });
var telegram_notify_1 = require("./telegram-notify");
Object.defineProperty(exports, "sendHeartbeatTelegramNotification", { enumerable: true, get: function () { return telegram_notify_1.sendHeartbeatTelegramNotification; } });
Object.defineProperty(exports, "sendBudgetWarningTelegram", { enumerable: true, get: function () { return telegram_notify_1.sendBudgetWarningTelegram; } });
var agent_secrets_1 = require("./agent-secrets");
Object.defineProperty(exports, "setSecret", { enumerable: true, get: function () { return agent_secrets_1.setSecret; } });
Object.defineProperty(exports, "getSecret", { enumerable: true, get: function () { return agent_secrets_1.getSecret; } });
Object.defineProperty(exports, "listSecrets", { enumerable: true, get: function () { return agent_secrets_1.listSecrets; } });
Object.defineProperty(exports, "deleteSecret", { enumerable: true, get: function () { return agent_secrets_1.deleteSecret; } });
Object.defineProperty(exports, "resolveSecretRefs", { enumerable: true, get: function () { return agent_secrets_1.resolveSecretRefs; } });
var retry_policy_service_1 = require("./retry-policy-service");
Object.defineProperty(exports, "applyWakeupFailure", { enumerable: true, get: function () { return retry_policy_service_1.applyWakeupFailure; } });
Object.defineProperty(exports, "buildWakeupIdempotencyKey", { enumerable: true, get: function () { return retry_policy_service_1.buildWakeupIdempotencyKey; } });
Object.defineProperty(exports, "classifyOrchestrationFailure", { enumerable: true, get: function () { return retry_policy_service_1.classifyOrchestrationFailure; } });
Object.defineProperty(exports, "computeRetryDelayMs", { enumerable: true, get: function () { return retry_policy_service_1.computeRetryDelayMs; } });
Object.defineProperty(exports, "resolveMaxRetries", { enumerable: true, get: function () { return retry_policy_service_1.resolveMaxRetries; } });
var circuit_breaker_service_1 = require("./circuit-breaker-service");
Object.defineProperty(exports, "AgentCircuitOpenError", { enumerable: true, get: function () { return circuit_breaker_service_1.AgentCircuitOpenError; } });
Object.defineProperty(exports, "ensureAgentCircuitReady", { enumerable: true, get: function () { return circuit_breaker_service_1.ensureAgentCircuitReady; } });
Object.defineProperty(exports, "getAgentCircuitSnapshot", { enumerable: true, get: function () { return circuit_breaker_service_1.getAgentCircuitSnapshot; } });
Object.defineProperty(exports, "isAgentCircuitOpen", { enumerable: true, get: function () { return circuit_breaker_service_1.isAgentCircuitOpen; } });
Object.defineProperty(exports, "recordAgentCircuitFailure", { enumerable: true, get: function () { return circuit_breaker_service_1.recordAgentCircuitFailure; } });
Object.defineProperty(exports, "recordAgentCircuitSuccess", { enumerable: true, get: function () { return circuit_breaker_service_1.recordAgentCircuitSuccess; } });
var checkpoint_service_1 = require("./checkpoint-service");
Object.defineProperty(exports, "createHeartbeatRunCheckpoint", { enumerable: true, get: function () { return checkpoint_service_1.createHeartbeatRunCheckpoint; } });
Object.defineProperty(exports, "listHeartbeatRunCheckpoints", { enumerable: true, get: function () { return checkpoint_service_1.listHeartbeatRunCheckpoints; } });
Object.defineProperty(exports, "parseCheckpointState", { enumerable: true, get: function () { return checkpoint_service_1.parseCheckpointState; } });
Object.defineProperty(exports, "queueHeartbeatRunReplay", { enumerable: true, get: function () { return checkpoint_service_1.queueHeartbeatRunReplay; } });
var delegation_service_1 = require("./delegation-service");
Object.defineProperty(exports, "createAgentDelegation", { enumerable: true, get: function () { return delegation_service_1.createAgentDelegation; } });
Object.defineProperty(exports, "listRunDelegations", { enumerable: true, get: function () { return delegation_service_1.listRunDelegations; } });
Object.defineProperty(exports, "listWorkflowDelegations", { enumerable: true, get: function () { return delegation_service_1.listWorkflowDelegations; } });
Object.defineProperty(exports, "updateDelegationStatusByChildRun", { enumerable: true, get: function () { return delegation_service_1.updateDelegationStatusByChildRun; } });
var workflow_service_1 = require("./workflow-service");
Object.defineProperty(exports, "createWorkflowTemplate", { enumerable: true, get: function () { return workflow_service_1.createWorkflowTemplate; } });
Object.defineProperty(exports, "updateWorkflowTemplate", { enumerable: true, get: function () { return workflow_service_1.updateWorkflowTemplate; } });
Object.defineProperty(exports, "getWorkflowTemplate", { enumerable: true, get: function () { return workflow_service_1.getWorkflowTemplate; } });
Object.defineProperty(exports, "listWorkflowTemplates", { enumerable: true, get: function () { return workflow_service_1.listWorkflowTemplates; } });
Object.defineProperty(exports, "createWorkflowRun", { enumerable: true, get: function () { return workflow_service_1.createWorkflowRun; } });
Object.defineProperty(exports, "advanceWorkflowRun", { enumerable: true, get: function () { return workflow_service_1.advanceWorkflowRun; } });
Object.defineProperty(exports, "listWorkflowRuns", { enumerable: true, get: function () { return workflow_service_1.listWorkflowRuns; } });
Object.defineProperty(exports, "getWorkflowRunDetail", { enumerable: true, get: function () { return workflow_service_1.getWorkflowRunDetail; } });
Object.defineProperty(exports, "syncWorkflowStepFromHeartbeatRun", { enumerable: true, get: function () { return workflow_service_1.syncWorkflowStepFromHeartbeatRun; } });
var ops_service_1 = require("./ops-service");
Object.defineProperty(exports, "getOrchestrationOpsSnapshot", { enumerable: true, get: function () { return ops_service_1.getOrchestrationOpsSnapshot; } });
var permission_grants_1 = require("./permission-grants");
Object.defineProperty(exports, "hasPermission", { enumerable: true, get: function () { return permission_grants_1.hasPermission; } });
Object.defineProperty(exports, "requirePermission", { enumerable: true, get: function () { return permission_grants_1.requirePermission; } });
Object.defineProperty(exports, "grantPermission", { enumerable: true, get: function () { return permission_grants_1.grantPermission; } });
Object.defineProperty(exports, "revokePermission", { enumerable: true, get: function () { return permission_grants_1.revokePermission; } });
Object.defineProperty(exports, "listPermissions", { enumerable: true, get: function () { return permission_grants_1.listPermissions; } });
Object.defineProperty(exports, "setPermissions", { enumerable: true, get: function () { return permission_grants_1.setPermissions; } });
